'в кино':
  afisha:
    kinds:
      - movie

  organization:
    suborganizations:
      - entertainment
    categories:
      - кинотеатры

'в кафе/бар/ресторан':
  afisha:
    kinds: []

  organization:
    suborganizations:
      - meal

    categories:
      - кафе
      - рестораны
      - бары
      - кофейни
      - банкетные залы
      - кондитерские

'в сауну':
  afisha:
    kinds: []

  organization:
    suborganizations:
      - sauna

    categories: []

'в ночной клуб':
  afisha:
    kinds:
      - party

  organization:
    suborganizations:
      - entertainment

    categories:
      - ночные клубы

'в театр':
  afisha:
    kinds:
      - spectacle

  organization:
    suborganizations:
      - culture

    categories:
      - театры

'в музей':
  afisha:
    kinds:
      - exhibition

  organization:
    suborganizations:
      - culture

    categories:
      - музеи

'на концерт':
  afisha:
    kinds:
      - concert

  organization:
    suborganizations:
      - entertainment

    categories:
      - филармонии
      - ночные клубы
      - театры
      - бары

'поиграть на бильярде':
  afisha:
    kinds:
      - sportsevent

  organization:
    suborganizations:
      - entertainment

    categories:
      - бильярдные залы

'играть в боулинг':
  afisha:
    kinds:
      - sportsevent

  organization:
    suborganizations:
      - entertainment

    categories:
      - боулинг

'попеть караоке':
  afisha:
    kinds: []

  organization:
    suborganizations:
      - meal
      - entertainment

    categories:
      - бары
      - рестораны
      - караоке

'заняться спортом':
  afisha:
    kinds:
      - sportsevent

  organization:
    suborganizations:
      - sport

    categories:
      - фитнес
      - танцы
      - тренажерные залы
      - спортивные школы
      - спортивные секции
      - боевые искусства
      - катки
      - йога
      - шахматные школы
      - ипподромы
      - стадионы
      - конные клубы
      - лыжные базы
      - игровые виды спорта

'учиться':
  afisha:
    kinds:
      - masterclass

  organization:
    suborganizations:
      - creation

    categories:
      - развивающие занятия
      - мастерилки
      - музыкальные студии
      - иностранные языки
      - изо студии
      - фотошколы
      - театральные студии

'прогуляться':
  afisha:
    kinds: []

  organization:
    suborganizations:
      - entertainment

    categories:
      - аттракционы

'в гости на чай':
  afisha:
    kinds: []

  organization:
    suborganizations: []

    categories: []

'за покупками':
  afisha:
    kinds: []

  organization:
    suborganizations: []

    categories: []

'покататься на машине':
  afisha:
    kinds: []

  organization:
    suborganizations: []

    categories: []
