billiard:
  categories:
    - Бильярдные залы

  features:
    - vip-зал
    - wi-fi
    - аэрохоккей
    - бизнес-ланч
    - боулинг
    - винная карта
    - детское меню
    - зал для некурящих
    - кальян
    - караоке
    - коктейльная карта
    - кофейная карта
    - нарды
    - разливное пиво
    - сигарная карта
    - спортивная трансляция
    - спортивные трансляции
    - теннис
    - тир
    - фоновая музыка
    - чайная карта
    - шахматы
    - шоу программа
    - элитные чаи

  offers:
    - американский пул
    - индивидуальные тренировки
    - клубная карта
    - организация турниров
    - подарочные сертификаты
    - русский бильярд
    - снукер

salon_center:
  singularized_categories:
    Парикмахерские: Парикмахерская
    SPA-салоны: SPA-салон

  categories:
    - SPA-салоны
    - Визаж-студии
    - Массажные салоны
    - Ногтевые студии
    - Парикмахерские
    - Студии загара
    - Тату-салоны
    - Косметические салоны

  features: []

  offers:
    - SPA-процедура
    - Визаж
    - Женская стрижка
    - Маникюр
    - Массаж
    - Мужская стрижка
    - Педикюр
    - Солярий

hotel:
  categories:
    - Гостиницы
    - Хостелы
    - Апартаменты

  features:
    - автостоянка
    - банкетный зал
    - бассеин
    - бесплатный Wi-Fi
    - платный Wi-Fi
    - зал конференций
    - настольные игры
    - сауна
    - спутниковое телевидение

  offers:
    - завтрак
    - обед
    - ужин
    - камера хранения

recreation_center:
  categories:
    - Базы отдыха
    - Загородные дома

  features:
    - бесплатный Wi-Fi
    - платный Wi-Fi
    - автостоянка
    - банкетный зал
    - баня
    - бассеин
    - зал конференций
    - коттеджи
    - летняя веранда
    - сауна

  offers:
    - завтрак
    - обед
    - ужин
    - аренда автомобиля
    - бильярд
    - аренда мангала
    - массаж
    - оздоровительные процедуры
    - проведение конференций
    - прокат катамаранов
    - прокат квадрациклов
    - прокат лодок
    - прокат снегоходов

room:
  features:
    - односпальная кровать
    - двуспальная кровать
    - двухъярусная кровать
    - кондиционер
    - телевизор
    - стиральная машина
    - холодильник
    - кухня
    - душ
    - ванная комната
    - отдельный санузел

travel:
  categories:
    - Туристические агентства
    - Билетные сервисы

  features:
    - услуги для поездок по России
    - услуги для поездок зарубеж

  offers:
    - горячие путевки
    - автобусные туры
    - экскурсионные туры
    - ранее бронирование
    - круизы
    - свадебные путешествия
    - лечебные туры
    - шоп-туры
    - событийные туры

car_service_center:
  categories:
    - Кузовной ремонт
    - Автосигнализации
    - Автозвук
    - Ремонт ходовой части
    - Ремонт автостекол
    - СТО
    - Ремонт автоэлектрики
    - Ремонт двигателя
    - Мелкосрочный ремонт

  features: []

  offers:
    - кузовной ремонт
    - электрика
    - ремонт двигателя
    - ремонт ходовой части
    - тюнинг
    - мелкосрочный ремонт
    - шиномонтаж
    - ремонт коробки передач
    - автостекла
    - ТО

car_sales_center:
  categories:
    - Легковые автомобили
    - Грузовые и спецтехника
    - Мототехника
    - Водный транспорт

  features:
    - новые
    - с пробегом

  offers:
    - кредит
    - лизинг
    - рассрочка
    - сервисное обслуживание
    - продажа запчастей

car_wash:
  categories:
    - Автомойки

  features:
    - ручная мойка
    - автоматическая мойка
    - безконтактная мойка
    - химчистка салона
    - мойка грузовых автомобилей
    - с залом ожидания
    - wi-fi

  offers:
    - Ополаскивание кузова
    - Мойка кузова
    - Комплексная мойка
    - Полировка кузова
    - Полировка салона
    - Влажная уборка салона
    - Химчистка салона
    - Мойка двигателя
    - Уборка багажника
    - Другие услуги


creation:
  categories:
    - Изо студии
    - Иностранные языки
    - Мастерилки
    - Музыкальные студии
    - Развивающие занятия
    - Театральные студии
    - Фотошколы
    - Киностудии
    - Клубы по интересам
    - Компьютерный мир
    - Конструирование
    - Другое

  features:
    - академический вокал
    - аккордеон
    - актерское мастерство
    - актёрское мастерство
    - английский язык
    - ансамблевое пение
    - аппликации
    - аппликация
    - батик
    - баян
    - бисероплетение
    - витражное искусство
    - вокал
    - выжигание
    - вязание
    - гармонь
    - гитара
    - грамматика
    - губная гармоника
    - декупаж
    - джазовый вокал
    - дизайн одежды
    - для девочек
    - для мам
    - живопись
    - звукорежиссура
    - изготовление интерьерной куклы
    - изготовление мягкой игрушки
    - изготовление театральной игрушки
    - имидж
    - интеллектуальное развитие
    - история
    - караоке
    - квилинг
    - квиллинг
    - квн
    - кино-видео съемка
    - киноискусство
    - композиция
    - компьютерная грамотность
    - конструирование
    - кубики зайцева
    - кукольный театр
    - лепка
    - логика
    - логопедические занятия
    - логоритмика
    - макетирование
    - малыш и мама
    - математика
    - методика зайцева
    - методика монтессори
    - методика орфа
    - моделирование одежды
    - мотодика железновой
    - музыкальные занятия
    - музыкальные инструменты
    - мультипликация
    - мыловарение
    - настольный театр
    - немецкий язык
    - ногтевой дизайн
    - обучение чтению
    - окружающий мир
    - опыты и исследования
    - оригами
    - основы театра
    - основы флористики
    - пальчиковый театр
    - подвижные игры
    - подготовка к школе
    - поделки из бересты
    - постановка спектаклей
    - проектирование зданий
    - развитие речи
    - раннее развитие
    - рисование
    - рисование комикса
    - ритмика
    - робото-конструирование
    - роспись
    - рукоделие
    - саксофон
    - синтезатор
    - скрапбукинг
    - скрипка
    - сольное пение
    - сольфеджио
    - стиль
    - сценическая речь
    - сценические движения
    - сюжетно-ролевые игры
    - творческие встречи
    - телевидение
    - теневой театр
    - ударные
    - флейта
    - фольклор
    - фортепиано
    - французский язык
  offers:

culture:
  categories:
    - Библиотеки
    - Дворцы культуры
    - Музеи
    - Планетарии
    - Театры
    - Филармонии

  features:
    - кукольные представления
    - спектакли для детей

  offers: []

entertainment:
  categories:
    - Антикафе
    - Аттракционы
    - Бильярдные залы
    - Боулинг
    - Караоке
    - Кинотеатры
    - Ночные клубы
    - Пейнтбол
    - Развлекательные комплексы
    - Страйкбол
    - Стриптиз-бары

  features:
    - vip-зал
    - wi-fi
    - аэрохоккей
    - бизнес-ланч
    - боулинг
    - винная карта
    - детское меню
    - зал для некурящих
    - кальян
    - караоке
    - коктейльная карта
    - кофейная карта
    - нарды
    - разливное пиво
    - сигарная карта
    - спортивная трансляция
    - спортивные трансляции
    - теннис
    - тир
    - фоновая музыка
    - чайная карта
    - шахматы
    - шоу программа
    - элитные чаи

  offers:
    - американский пул
    - индивидуальные тренировки
    - клубная карта
    - организация турниров
    - подарочные сертификаты
    - русский бильярд
    - снукер

meal:
  categories:
    - Банкетные залы
    - Бары
    - Детские кафе
    - Доставка еды
    - Кафе
    - Кейтеринг
    - Кондитерские
    - Кофейни
    - Пиццерии
    - Рестораны
    - Столовые
    - Суши-бары
    - Чайная

  cuisines:
    - Авторская
    - Азиатская
    - Американская
    - Арабская
    - Восточная
    - Вьетнамская
    - Гавайская
    - Грузинская
    - Европейская
    - Ирландская
    - Итальянская
    - Кавказская
    - Китайская
    - Корейская
    - Мексиканская
    - Русская
    - Сибирская
    - Славянская
    - Тайская
    - Татарская
    - Турецкая
    - Узбекская
    - Японская

  features:
    - chill out
    - vip-зал
    - wi-fi
    - x-box
    - бильярд
    - блюда на вынос
    - боулинг
    - вегетарианское меню
    - винная карта
    - гриль-меню
    - дартц
    - детское меню
    - доставка пиццы
    - живая музыка
    - зал для некурящих
    - кальян
    - караоке
    - коктейльная карта
    - кофейная карта
    - летняя веранда
    - нарды
    - настольный футбол
    - разливное пиво
    - сигарная карта
    - спортивные трансляции
    - фоновая музыка
    - чайная карта
    - шахматы
    - шашки
    - шоу программа
    - элитные чаи
  menu_categories:
    - Основное меню
    - Банкетное меню
    - Бизнес ланч
    - Барная карта
  menu_positions:
    - Безалкогольные напитки
    - Выпечка
    - Горячие блюда
    - Десерты
    - Молочные коктейли
    - Чайные коктейли
    - Лимонады
    - Крепкие напитки
    - Пиво
    - Пицца
    - Салаты и закуски
    - Сигареты
    - Слабоалкогольные напитки
    - Чай/Кофе
    - Японская кухня
  offers:
    - банкеты
    - бизнес-ланч
    - выездное обслуживание
    - завтраки
    - закрытые вечеринки
    - корпоративные вечера
    - поминальные обеды
    - свадьбы
    - свежая выпечка
    - торжества
    - фуршеты
    - чайные церемонии
    - юбилеи

sauna:
  categories:
    - Сауны

  features:
    - wi-fi
    - бассейн
    - бильярд
    - бильярдная
    - кабельное тв
    - кальян
    - караоке
    - нарды
    - финская парная

  offers:
    - баня
    - инфракрасная парная
    - кедровая фитопаробочка
    - русская парная
    - русско-турецкая баня
    - турецкая парная
    - финская парная

sport:
  categories:
    - Тренажёрные залы
    - Фитнес
    - Танцы
    - Художественная гимнастика
    - Йога
    - Боевые искусства
    - Игровые виды спорта
    - Бассейны
    - Закаливание
    - Катки
    - Ледовые дворцы
    - Лыжные базы
    - Горнолыжные комплексы
    - Спортивные секции
    - Спортивные школы
    - Стадионы
    - Шахматные школы
    - Ипподромы
    - Конные клубы
    - Картинг
    - Профессиональные спортивные клубы
    - Спортивно-тактические клубы
    - Другое

  features: []

  offers:
    - Аэробика
    - Альпинизм
    - Водное поло
    - Волейбол
    - Гребля
    - Грепплинг
    - Дайвинг
    - Йога
    - Каратэ
    - Картинг
    - Клубная карта
    - Легкая атлетика
    - Пеинтболл
    - Плавание
    - Спортивный танец
    - Страйкболл
    - Стрип пластика
    - Тайский бокс
    - Тренажерный зал
    - Ушу
    - Футбол
    - Художественная гимнастика
    - Конная прогулка
    - Верховая езда
